spring:
  application:
    name: eureka-server
server:
  port: 2001
eureka:
  client:
    #是否将自己注册到Eureka Server 默认true.(由于当前应用就是Eureka Server,设为false)
    register-with-eureka: false
    #是否从Eureka Server获取注册信息 默认为true.(由于这是一个单点Eureka Server,无需同步其他的Eureka,故设为false)
    fetch-registry: false
    #设置与Eureka Server交互的地址,查询服务和注册服务都需要依赖这个地址,默认是http://localhost:8761/eureka 多地址,分隔
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
